spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.49.2:31577/realms/kubernetes-spring
          jwk-set-uri: http://192.168.49.2:31577/realms/kubernetes-spring/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8080