spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.192.168.49.2.nip.io/realms/kubernetes-spring
          jwk-set-uri: https://keycloak.192.168.49.2.nip.io/realms/kubernetes-spring/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8080