# **** OpenAPI-Schnittstelle ****
springdoc:
  api-docs:
    path: /openapi/api-docs
  swagger-ui:
    path: /openapi/swagger-ui.html
# *******************************

# ********** Logging ************
logging:
  level:
    org:
      springframework:
        web: DEBUG
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
# *******************************

server:
  port: 8080

