# *********** Spring ************
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/SpringBootKeycloak
          jwk-set-uri: http://localhost:8090/realms/SpringBootKeycloak/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: app
            client-secret: 5uw6nSWtwD9IWhB1kJvmh8PFf903QCza
            scope: openid,profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/SpringBootKeycloak
  #  h2:
  #    console:
  #      enabled: true
  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    password: sa
  #  jpa:
  #    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG