# *********** Spring ************
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.49.2:31577/realms/kubernetes-spring
          jwk-set-uri: http://192.168.49.2:31577/realms/kubernetes-spring/protocol/openid-connect/certs
  #  h2:
  #    console:
  #      enabled: true
  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    password: sa
  #  jpa:
  #    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
# *******************************

# **** OpenAPI-Schnittstelle ****
springdoc:
  api-docs.path: /openapi/api-docs
  swagger-ui.path: /openapi/swagger-ui.html
# *******************************

# ********** Logging ************
logging:
  level:
    org:
      springframework:
        web: DEBUG
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
# *******************************

server:
  port: 8080

