server {
  include /etc/nginx/extra-conf.d/*.conf;

  listen 80;
  server_name ui-angular;

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
   }

  location /api {
    proxy_pass https://kubernetes-spring:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
   }
 }
