name: kubernetes-spring-publish

on: [ push ]

jobs:
  publish-kubernetes-spring-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the kubernetes-spring Docker image
        run: |
          echo $CR_PAT | docker login ghcr.io -u flo.scholz@gmx.net --password-stdin
          docker build . --tag ghcr.io/schoflo/kubernetes-spring:latest
          docker push ghcr.io/schoflo/kubernetes-spring
        env:
          CR_PAT: ${{ secrets.CR_PAT }}