name: kubernetes-spring-publish

on: [ push ]
jobs:
  publish-kubernetes-spring-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the kubernetes-spring Docker image
        run: |
          docker build ./business-service --tag ghcr.io/schoflo/kubernetes-spring:latest
          docker push ghcr.io/schoflo/kubernetes-spring:latest